package com.servicio;
// Generated 31-jul-2013 16:03:15 by Hibernate Tools 3.2.1.GA



/**
 * Credito generated by hbm2java
 */
public class Credito  implements java.io.Serializable {


     private String id;
     private String tipo;
     private Long monto;
     private int interes;

    public Credito() {
    }

	
    public Credito(String id) {
        this.id = id;
    }
    public Credito(String id, String tipo, Long monto, Integer interes) {
       this.id = id;
       this.tipo = tipo;
       this.monto = monto;
       this.interes = interes;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Long getMonto() {
        return this.monto;
    }
    
    public void setMonto(Long monto) {
        this.monto = monto;
    }
    public int getInteres() {
        return this.interes;
    }
    
    public void setInteres(Integer interes) {
        this.interes = interes;
    }

}


